# Generated by Django 5.0.4 on 2024-06-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_tag_work_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
