# Generated by Django 5.0.4 on 2024-06-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_remove_work_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_me/')),
                ('primary_caption', models.CharField(max_length=100)),
                ('secondary_caption', models.CharField(max_length=100)),
            ],
        ),
    ]
