# Generated by Django 5.0.4 on 2024-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0004_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='primary_caption',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='secondary_caption',
            field=models.CharField(max_length=500),
        ),
    ]
