# Generated by Django 5.0.4 on 2024-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0005_alter_aboutme_primary_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='We can make it together', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='primary_caption',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='secondary_caption',
            field=models.TextField(max_length=500),
        ),
    ]
