# Generated by Django 5.0.4 on 2024-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0006_aboutme_title_alter_aboutme_primary_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_background_image', models.ImageField(upload_to='background_image/')),
                ('main_heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
    ]
