# Generated by Django 5.0.4 on 2024-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0008_alter_maindetails_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
